spring:
  application:
    name: spring-boot-executable

logging:
  level:
    root: info
    com.geniusver: info

# Profiles
---
spring:
  config:
    activate:
      on-profile: profile-1
server:
  port: 8000
